### ISSUE TITLE
How to install the vapor old version @3 with this repo ? 

### ISSUE THREAD

**Issue by IOLOII** [vapor-community/apns#4]
How to install the vapor old version @3 with this repo ? Because if I install the vapor with Xcode version I'm using now directly 13.1 , it prompts that it is not compatible with the latest version 4.0, so I need to install version 3.0, but I didn't find a suitable document tutorial.

<img width="530" alt="image" src="https://github.com/vapor-community/apns/assets/34856171/6aec7ef0-82c7-4d6b-9a43-fa09bfba7ada">
<img width="640" alt="image" src="https://github.com/vapor-community/apns/assets/34856171/1d40326f-10d9-4063-985f-cc93c9ebfd3b">
<img width="646" alt="image" src="https://github.com/vapor-community/apns/assets/34856171/0135c07a-22e4-47f2-bf2f-e08e533a46e2">
<img width="242" alt="image" src="https://github.com/vapor-community/apns/assets/34856171/110a8ce7-e295-4761-a6bf-c041535a120e">

Because my macos has not been updated, and I don't want to update to the latest macos, so I can't update to the latest xcode, so I have a question. Thank you.

**Comment by 0xTim** [comment]
@IOLOII I'm assuming you're trying to install the toolbox? (Not sure why you picked this repo to open the issue). You can install an old version with `brew install vapor@[version-number]` but this might be a Homebrew issue as we don't specify the Xcode version required. You can clone the templates manually worst case, e.g. https://github.com/vapor/template-bare/tree/main

Note that the latest Swift version you can install is 5.6 which is no longer supported by Vapor. You would probably be better off using Docker containers and Swift on Linux with VSCode

**Comment by IOLOII** [comment]
> @IOLOII I'm assuming you're trying to install the toolbox? (Not sure why you picked this repo to open the issue). You can install an old version with `brew install vapor@[version-number]` but this might be a Homebrew issue as we don't specify the Xcode version required. You can clone the templates manually worst case, e.g. https://github.com/vapor/template-bare/tree/main
> 
> 
> 
> Note that the latest Swift version you can install is 5.6 which is no longer supported by Vapor. You would probably be better off using Docker containers and Swift on Linux with VSCode

Because this repo was found in the awsome list. I want to learn this project, and the readme file of this project is written about the project that needs vapor3. When I tried to install and run it directly, I encountered the above-related problems, so I asked questions. I may have disturbed you, but thank you for your reply.

**Comment by 0xTim** [comment]
Ah yeah I should probably archive this - this is what you want https://github.com/swift-server-community/APNSwift
